<Project>                                                                                                                                                                                              
  <PropertyGroup>                                                                                                                                                                                      
    <UseArtifactsOutput>true</UseArtifactsOutput>                                                                                                                                                      
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.meta</DefaultItemExcludes>                                                                                                                                
  </PropertyGroup>                                                                                                                                                                                     
</Project>