<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <ProjectReference Include="..\DuckDoku.Application\DuckDoku.Application.csproj" />
      <ProjectReference Include="..\..\..\shared\DuckDoku.Contracts\DuckDoku.Contracts.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

</Project>
