<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\DuckDoku.Domain\DuckDoku.Domain.csproj" />
      <ProjectReference Include="..\..\..\shared\DuckDoku.Puzzle\DuckDoku.Puzzle.csproj" />
      <ProjectReference Include="..\..\..\shared\DuckDoku.Contracts\DuckDoku.Contracts.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
